name: maktrack
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  flutter_otp_text_field: ^1.5.1+1
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  get: ^4.7.2

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  fl_chart: ^0.70.2
  loading_animation_widget: ^1.3.0
  smooth_page_indicator: ^1.2.1
  percent_indicator: ^4.2.4

  flutter_staggered_grid_view: ^0.7.0

  date_picker_timeline: 1.2.5
  intl: ^0.18.0

  sqflite: ^2.4.1
  flutter_staggered_animations: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/mLogo.png"
  min_sdk_android: 21



  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/Icons/
    - assets/onboarding/



  fonts:
     - family: PromoTest
       fonts:
         - asset: assets/fonts/PromoTest-Bold-BF63b788015fdbf.otf
         - asset: assets/fonts/PromoTest-Medium-BF63b78802b0fd1.otf
         - asset: assets/fonts/PromoTest-Regular-BF63b7880272a33.otf

