name: maktrack
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  dot_navigation_bar: ^1.0.2
  table_calendar: ^3.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter





  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/

#  example:
  fonts:
     - family: PromoTest
       fonts:
         - asset: assets/fonts/PromoTest-Bold-BF63b788015fdbf.otf
         - asset: assets/fonts/PromoTest-Medium-BF63b78802b0fd1.otf
         - asset: assets/fonts/PromoTest-Regular-BF63b7880272a33.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
